name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1 # Change to your preferred region
  ECR_REPOSITORY_SERVER: shopmart-server
  ECR_REPOSITORY_CLIENT: shopmart-client

jobs:
  deploy:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get AWS Account ID
      id: account-id
      run: echo "id=$(echo ${{ steps.login-ecr.outputs.registry }} | cut -d'.' -f1)" >> $GITHUB_OUTPUT

    # --- SERVER DEPLOYMENT ---
    - name: Build, tag, and push Server image to Amazon ECR
      id: build-server
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_SERVER:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY_SERVER:latest ./server
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_SERVER:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_SERVER:latest

    # --- CLIENT DEPLOYMENT ---
    - name: Build, tag, and push Client image to Amazon ECR
      id: build-client
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:latest ./client
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:latest

